swagger: "2.0"
info:
  description: "Transaction API"
  version: "1.0.0"
  title: "Transaction API"
basePath: /api/transactions
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /transactions:
    get:
      summary: "Get a list of all transactions"
      responses:
        200:
          description: "Successful response"
          schema:
            type: array
            items:
              $ref: "#/definitions/TransactionResponse"
  /transactions/{transactionId}:
    get:
      summary: "Get a transaction by ID"
      parameters:
        - name: transactionId
          in: path
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: "Successful response"
          schema:
            $ref: "#/definitions/TransactionResponse"
    post:
      summary: "Create a new transaction"
      parameters:
        - name: transaction
          in: body
          required: true
          schema:
            $ref: "#/definitions/TransactionRequest"
      responses:
        201:
          description: "Transaction created successfully"
definitions:
  TransactionResponse:
    type: object
    properties:
      id:
        type: integer
        format: int64
      amount:
        type: number
        format: double
      description:
        type: string
      date:
        type: string
        format: date-time
  TransactionRequest:
    type: object
    properties:
      amount:
        type: number
        format: double
      description:
        type: string
    required:
      - amount
      - description
